#! /bin/bash

############
## Written by maxime cheminade aka Tachikomas on 2017 for Ubuntu Party Paris Only
############


echo "Welcome to the fast install tool for Mac Os"
echo "All logs will be forwarded to /tmp/logs/FastUbuntu"
echo "please send issue on Tchakatak GitHub if you find !"
sleep 3

echo "Option 1 : How to disable SIP mac !!!!!REQUIRED!!!!"
echo "Option 2 : Full prepare and install EFI (NEED SIP DISABLE)"
echo "Option 3 : Only install EFI module (NEED SIP DISABLE)"

### WIP echo "after a complet run, press 4 to resize / partition and make free space for ubuntu (20Gb)"

PS3='Please enter your choice: '
options=("1" "2" "3" "4" "Quit")
select opt in "${options[@]}"
do
case $opt in
		"1")
				echo "To disable SIP, reboot your mac and enter Recovery Menu using CMD+R"
				echo "Open a terminal, and enter "csrutil disable" and reboot"
				echo "Dont forget to re enable SIP using "csrutil enable" after install "
				echo "actual status is :"
				csrutil status
				;;
		"2")
		    echo "Creating Logs Directory"
				mkdir /tmp/logs/
				mkdir /tmp/logs/FastUbuntu
				sleep 1
				echo "Terminated"

				sleep 2
				echo "Verificating Volume on main disk"
				sudo diskutil verifyVolume / > /tmp/logs/FastUbuntu/verifyVolume.log
				echo "Verification Termniated, reparing broken stuff"
				sudo diskutil repairVolume / > /tmp/logs/FastUbuntu/repairVolume.log
				echo "Verification Completed"
				sleep 2

				echo "Installing Brew"
				/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/logs/FastUbuntu/brewinstall.log
				echo "brew install terminated"
				sleep 5

				echo "Using brew to download and install wget"
				brew install wget > /tmp/logs/FastUbuntu/wgetinstall.log
				sleep 3
				echo "Brew finish to installed necessary library on your Mac"
				sleep 5

				echo "Downloading Refind"
				cd /tmp/
				wget https://downloads.sourceforge.net/project/refind/0.10.5/refind-bin-0.10.5.zip > /tmp/logs/FastUbuntu/wgetrefind.log
				unzip refind-bin-0.10.5.zip > /tmp/logs/FastUbuntu/unziprefind.log
				cd /tmp/refind-bin-0.10.5
				sudo bash /tmp/refind-bin-0.10.5/refind-install > /tmp/logs/FastUbuntu/refindinstall.log
				rm /tmp/refind-bin-0.10.5.zip
				rm -R /tmp/refind-bin-0.10.5

				echo "if ALL success, you can reboot and install Ubuntu with your usb key or live CD"
				sleep 5
				echo "if it don't , you have probably SIP activated. Check the logs !"
				echo "use Option 1 to see how disable it, and chose after option 3 to reinstall only refind"
				echo "Have fun on Ubuntu :)"
				sleep 3
				break
				;;
		"3")
				echo "Reinstall only Refind"
				cd /tmp/
				wget https://downloads.sourceforge.net/project/refind/0.10.5/refind-bin-0.10.5.zip > /tmp/logs/FastUbuntu/wgetrefind.log
				unzip refind-bin-0.10.5.zip > /tmp/logs/FastUbuntu/unziprefind.log
				cd /tmp/refind-bin-0.10.5
		    sudo bash /tmp/refind-bin-0.10.5/refind-install > /tmp/logs/FastUbuntu/refindinstall.log
				rm /tmp/refind-bin-0.10.5.zip
				rm -R /tmp/refind-bin-0.10.5
				echo "if ALL success, you can reboot and install Ubuntu with your usb key or live CD"
				sleep 5
				echo "if it don't , you have probably SIP activated. Check the logs !"
				echo "use Option 1 to see how disable it, and chose after option 3 to reinstall only refind"
		    echo "Have fun on Ubuntu :)"
				sleep 3
				break
				;;
		"4")
				break
				# Work in progress
				;;
		"Quit")
				break
				;;
		*) echo invalid option;;
esac
done
